//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public short ProductID { get; set; }
        public string Name { get; set; }
        public string Rules { get; set; }
    }
}
