//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBundle_Product
    {
        public short BundleID { get; set; }
        public string Bundle { get; set; }
        public short ProductID { get; set; }
        public string Product { get; set; }
    }
}
